import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

import 'catapi.dart';
class dogfatapi extends StatefulWidget {
  const dogfatapi({super.key});

  @override
  State<dogfatapi> createState() => _dogfatapiState();
}

class _dogfatapiState extends State<dogfatapi> {
  Map<String,dynamic> bodyData={};
  Future<Catclass> getData() async{
    try {
      var apiResponse = await http.get(Uri.parse("https://dog.ceo/api/breeds/image/random"));

      if (apiResponse.statusCode == 200 || apiResponse.statusCode == 201) {
        bodyData = jsonDecode(apiResponse.body);
        ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text("Data fetched successfully")));
        return Catclass.fromJson(bodyData);
      }
      else {
        throw Exception(apiResponse.body);
      }
    }
    catch(e){
      throw Exception(e);

    }
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Catfact Api"),
      ),
      body: FutureBuilder(future:getData() , builder: (context,snapshot){
        if(snapshot.connectionState==ConnectionState.waiting){
          return CircularProgressIndicator();
        }
        else if(snapshot.hasError){
          return Text("Error :${snapshot.error}");
        }
        else if(snapshot.hasData){
          var myData=snapshot.data!;

          return Column(
            children: [
              Image.network(bodyData["message"]),
              Text(bodyData["status"].toString())

            ],
          );
        }
        else{
          return Text("No data found");
        }
      }),
    );
  }
}
class Autogenerated {
  String? message;
  String? status;

  Autogenerated({this.message, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['status'] = this.status;
    return data;
  }
}
